
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

server:
  port: 8070

spring:
  application:
    name: schools
  datasource:
    url: jdbc:mysql://localhost:3306/school?createDatabaseIfNotExist=true&userSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

application:
  config:
    students-url: http://localhost:8222/api/students
